//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> SubcategoriaId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> PrecioCompra { get; set; }
        public Nullable<double> PrecioVenta { get; set; }
        public double Existencia { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UnidadId { get; set; }
        public Nullable<int> ProveedorId { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Subcategoria Subcategoria { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
